spring.application.name=it-projects-vk-spring
spring.datasource.url=jdbc:postgresql://localhost:5432/job_recommender_db
spring.datasource.username=postgres
spring.datasource.password=5432
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
app.logs.path=history/commands.txt
app.scheduling.delay=1m
app.repository.type=map