spring.datasource.url=jdbc:postgresql://localhost:5432/job_recommender_db
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always